config/routes.rb
Rails.application.routes.draw do

  get 'account/index'

  resources :users

  resources :wines
  resources :events

  get 'contact/index'

  
  get 'contact/index'

  get 'event/index'

  get 'catalogue/index'

  get 'welcome/index'

  resources :categories
  resources :wines
  resources :bottles do
    member do
      post :creer_link
    end
  end
  resources :statuses
  resources :orders do
    collection do
      post :submit_order
    end
  end

  resources :events
  resources :addresses
  resources :users

  root 'welcome#index'

  get 'admin' => 'admin#index'
  resources :sessions do
    collection do
      get 'login' => :new
      post 'login' => :create
      delete 'logout' => :destroy
    end
  end

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
	has_many :orders, :through => :links
	has_many :links
	belongs_to :wine
	validates_presence_of :wine_id
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :wines
	validates_presence_of :name
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
	belongs_to :bottle
	belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :status
	belongs_to :user
	has_many :bottles, :through => :links
	has_many :links
	validates_presence_of :status_id, :user_id

	def total_price
		total = 0
		self.links.each do |link|
			total = total + (link.number * link.bottle.price)
		end
		return total
	end
end

app/models/status.rb
class Status < ActiveRecord::Base
	has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :orders
  validates_presence_of :name, :password, :street, :npa, :city, :canton
end

app/models/wine.rb
class Wine < ActiveRecord::Base
	has_many :bottles
	belongs_to :category
	validates_presence_of :name, :desc, :vineyard, :grape
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: [:show, :edit, :update, :destroy]

  # GET /bottles
  # GET /bottles.json
  def index
    @bottles = Bottle.all
  end

  # GET /bottles/1
  # GET /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
    @wines = Wine.all
  end

  # GET /bottles/1/edit
  def edit
    @wines = Wine.all
  end

  # POST /bottles
  # POST /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)
    @wines = Wine.all

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: 'Bottle was successfully created.' }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1
  # PATCH/PUT /bottles/1.json
  def update
    @wines = Wine.all

    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: 'Bottle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: 'Bottle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def creer_link
    @bottle = Bottle.find(params[:id])
    @link = Link.new(link_params)
    @link.bottle = @bottle
    if @link.save
      puts "ajout à la liste"
      respond_to do | format |
        format.js {render 'create_link'}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bottle_params
      params.require(:bottle).permit(:price, :stock, :capacity, :wine_id)
    end

    def link_params
      params.require(:link).permit(:number)
    end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/catalogue_helper.rb
module CatalogueHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :'Vin' %><br /> 
    <%= f.collection_select :wine_id, @wines, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :"Contenance (cl)" %><br>
    <%= f.text_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :"Prix CHF" %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :Stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<%= render "layouts/admin_menu" %>

<div id="conteneur_intermediaire_right">
	<div class="article">
		<center>
		<h1>Editer la bouteille</h1>

		<%= render 'form' %>
		</center>
		<%= link_to 'Afficher', @bottle %> |
		<%= link_to 'Retour à la liste de bouteilles', bottles_path %>
	</div>
</div>

app/views/bottles/index.html.erb
<%= render "layouts/admin_menu" %>

<p id="notice"><%= notice %></p>

<div id="conteneur_intermediaire_right">  
  <div class="article">
    <h1>Liste des bouteilles disponibles</h1>
    <br/>

    <table border="1">
      <thead>
        <tr>
          <th>Prix</th>
          <th>Stock</th>
          <th>Contenance</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @bottles.each do |bottle| %>
          <tr>
            <td><%= bottle.price %></td>
            <td><%= bottle.stock %></td>
            <td><%= bottle.capacity %></td>
            <td><%= link_to 'Afficher', bottle %></td>
            <td><%= link_to 'Editer', edit_bottle_path(bottle) %></td>
            <td><%= link_to 'Supprimer', bottle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'Ajouter une nouvelle bouteille', new_bottle_path %>
  </div>
</div>

app/views/bottles/new.html.erb
<%= render "layouts/admin_menu" %>

<div id="conteneur_intermediaire_right">
	<div class="article">
		<center>
		<h2>Création de bouteilles</h2>
		<%= render 'form' %>
		</center>
		<%= link_to 'Retour à la liste des bouteilles', bottles_path %>
	</div>
</div>

app/views/bottles/show.html.erb
<%= render "layouts/admin_menu" %>

<p id="notice"><%= notice %></p>
<div id="conteneur_intermediaire_right">
	<div class="vin">
		<div class="image">
			<%= image_tag @bottle.wine.image, :class=>'normal' %>
		</div>

		<div class="description">
	    	<p><%= image_tag 'lieu.png', :class=>'icone' %><%= @bottle.wine.vineyard %></p>
	    	<p><%= image_tag 'vin.png', :class=>'icone' %><%= @bottle.wine.category.name%></p>
	      	<p><%= image_tag 'contenance.png', :class=>'icone' %><%= @bottle.capacity%> cl</p>
	      	<p><strong>DESCRIPTION</strong><br/><%= @bottle.wine.desc %></p>
	      	<br/>
	      	<p><strong>Prix : </strong><%= @bottle.price %> </p>
	      	<p><strong>Stock : </strong><%= @bottle.stock %> </p>
	    </div>

		<%= link_to 'Editer', edit_bottle_path(@bottle) %> |
		<%= link_to 'Retour à la liste des bouteilles', bottles_path %>
	</div>
</div>